In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
house_data=pd.read_csv('C:/projects/house_price_prediction/data/dataset.csv')
print(house_data)

     Bedrooms  Bathrooms  Square Feet  House Age  Location Rating  Price (USD)
0           3          1         2493         96                1     49733000
1           1          1          933         89                4     18457000
2           3          1         3938         38                3     78809000
3           3          1         3878         84                2     77470000
4           1          2         1747         48                4     34870000
..        ...        ...          ...        ...              ...          ...
995         2          1         2013          8                1     40347000
996         2          2         1959         80                3     39063000
997         3          1         1354         10                2     27212000
998         3          1         1203         95                4     23939000
999         1          1         1691          9                2     33855000

[1000 rows x 6 columns]

In [3]:
print(house_data.head(5))

   Bedrooms  Bathrooms  Square Feet  House Age  Location Rating  Price (USD)
0         3          1         2493         96                1     49733000
1         1          1          933         89                4     18457000
2         3          1         3938         38                3     78809000
3         3          1         3878         84                2     77470000
4         1          2         1747         48                4     34870000

In [4]:
print(house_data.columns)

Index(['Bedrooms', 'Bathrooms', 'Square Feet', 'House Age', 'Location Rating',
       'Price (USD)'],
      dtype='object')

In [5]:
house_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Bedrooms         1000 non-null   int64
 1   Bathrooms        1000 non-null   int64
 2   Square Feet      1000 non-null   int64
 3   House Age        1000 non-null   int64
 4   Location Rating  1000 non-null   int64
 5   Price (USD)      1000 non-null   int64
dtypes: int64(6)
memory usage: 47.0 KB

In [6]:
house_data.isnull().sum()

Bedrooms           0
Bathrooms          0
Square Feet        0
House Age          0
Location Rating    0
Price (USD)        0
dtype: int64

In [7]:
house_data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [8]:
house_data.describe()

,Bedrooms,Bathrooms,Square Feet,House Age,Location Rating,Price (USD)
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,1.964000,1.47300,2421.060000,49.333000,2.497000,4.838863e+07
std,0.820596,0.49952,897.796764,28.406955,1.122163,1.795831e+07
min,1.000000,1.00000,807.000000,0.000000,1.000000,1.604000e+07
25%,1.000000,1.00000,1643.000000,25.000000,2.000000,3.285975e+07
50%,2.000000,1.00000,2463.500000,48.000000,2.000000,4.926000e+07
75%,3.000000,2.00000,3176.750000,74.000000,4.000000,6.350325e+07
max,3.000000,2.00000,3999.000000,99.000000,4.000000,7.993600e+07

In [9]:
print(house_data['Bathrooms'].unique())
print(house_data['Bedrooms'].unique())
print(house_data['Location Rating'].unique())

[1 2]
[3 1 2]
[1 4 3 2]

In [10]:
print(house_data['Bathrooms'].corr(house_data['Price (USD)']))
print(house_data['Bedrooms'].corr(house_data['Price (USD)']))
print(house_data['House Age'].corr(house_data['Price (USD)']))
print(house_data['Location Rating'].corr(house_data['Price (USD)']))
print(house_data['Square Feet'].corr(house_data['Price (USD)']))

0.036709294297218205
-0.004174522165519579
-0.031220624373162906
-0.045680202816498344
0.9999864309415007

In [11]:
house_data[['Price (USD)','Square Feet']].head(5)

   Price (USD)  Square Feet
0     49733000         2493
1     18457000          933
2     78809000         3938
3     77470000         3878
4     34870000         1747

In [12]:
house_data[['Price (USD)','Square Feet']].tail(5)

     Price (USD)  Square Feet
995     40347000         2013
996     39063000         1959
997     27212000         1354
998     23939000         1203
999     33855000         1691

In [13]:
house_data[['Square Feet','Price (USD)']].max()

Square Feet        3999
Price (USD)    79936000
dtype: int64

In [14]:
house_data[['Square Feet','Price (USD)']].min()

Square Feet         807
Price (USD)    16040000
dtype: int64

In [15]:
house_data.corr(numeric_only=True)['Price (USD)']

Bedrooms          -0.004175
Bathrooms          0.036709
Square Feet        0.999986
House Age         -0.031221
Location Rating   -0.045680
Price (USD)        1.000000
Name: Price (USD), dtype: float64

In [16]:
house_data['per_sq_feet']=house_data['Price (USD)']/house_data['Square Feet']
house_data['per_sq_feet'].describe()

count     1000.000000
mean     19983.066798
std         52.029797
min      19739.285714
25%      19953.988724
50%      19988.349452
75%      20015.139070
max      20156.334232
Name: per_sq_feet, dtype: float64

In [17]:
house_data[['Square Feet','Price (USD)','per_sq_feet']]

     Square Feet  Price (USD)   per_sq_feet
0           2493     49733000  19949.057361
1            933     18457000  19782.422294
2           3938     78809000  20012.442864
3           3878     77470000  19976.792161
4           1747     34870000  19959.931311
..           ...          ...           ...
995         2013     40347000  20043.219076
996         1959     39063000  19940.275651
997         1354     27212000  20097.488922
998         1203     23939000  19899.418121
999         1691     33855000  20020.697812

[1000 rows x 3 columns]

In [18]:
house_data.drop('per_sq_feet',inplace=True,axis=1)

In [19]:
house_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Bedrooms         1000 non-null   int64
 1   Bathrooms        1000 non-null   int64
 2   Square Feet      1000 non-null   int64
 3   House Age        1000 non-null   int64
 4   Location Rating  1000 non-null   int64
 5   Price (USD)      1000 non-null   int64
dtypes: int64(6)
memory usage: 47.0 KB

In [20]:
X = house_data[['Bedrooms', 'Bathrooms', 'Square Feet', 'House Age', 'Location Rating']]
y = house_data['Price (USD)']

In [21]:
print(X.shape)
print(y.shape)

(1000, 5)
(1000,)

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,
    test_size=0.3,
    random_state=30
)

In [23]:
print(X_test.shape)
print(X_train.shape)
print(y_train.shape)
print(y_test.shape)

(300, 5)
(700, 5)
(700,)
(300,)

In [28]:
from sklearn.linear_model import LinearRegression
model1=LinearRegression()
model1.fit(X_train,y_train)

LinearRegression()

In [32]:
y_pred=model1.predict(X_test)
y_pred[:5]

array([35526000.        , 42984999.99999999, 33406000.        ,
       72278000.00000003, 70321000.00000001])

In [37]:
print(y_pred[:5])
print(y_test.iloc[:5].values)

[35526000.         42984999.99999999 33406000.         72278000.00000003
 70321000.00000001]
[35526000 42985000 33406000 72278000 70321000]

In [39]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [40]:
mae=mean_absolute_error(y_pred,y_test)
mse=mean_squared_error(y_pred,y_test)
r2=r2_score(y_pred,y_test)
print("MAE:",mae)
print("MSE:",mse)
print("R2:",r2)

MAE: 1.286466916402181e-08
MSE: 2.431388423929093e-16
R2: 1.0

In [41]:
train_pred = model1.predict(X_train)

print("Training R2:", r2_score(y_train, train_pred))
print("Testing R2:", r2_score(y_test, y_pred))

Training R2: 1.0
Testing R2: 1.0

In [42]:
print(model1.coef_)

[50000.         10000.00000001 20000.         -3000.
  1000.        ]

In [43]:
print(model1.intercept_)

-4.470348358154297e-08

In [44]:
from sklearn.ensemble import RandomForestRegressor
model2=RandomForestRegressor(random_state=30)
model2.fit(X_train,y_train)

RandomForestRegressor(random_state=30)

In [46]:
y_pred2=model2.predict(X_test)
print(y_pred2[:5])

[35414370. 42722460. 33405320. 72230930. 70354050.]

In [48]:
print("MAE:", mean_absolute_error(y_test, y_pred2))
print("MSE:", mean_squared_error(y_test, y_pred2))
print("R2:", r2_score(y_test, y_pred2))

MAE: 98410.16666666667
MSE: 16094074170.333334
R2: 0.9999478031814767

In [50]:
train_pred2 = model2.predict(X_train)

print("Training R2:", r2_score(y_train, train_pred2))
print("Testing R2:", r2_score(y_test, y_pred2))

Training R2: 0.9999929323219275
Testing R2: 0.9999478031814767

In [51]:
new_house = pd.DataFrame({
    'Bedrooms': [3],
    'Bathrooms': [2],
    'Square Feet': [2500],
    'House Age': [5],
    'Location Rating': [4]
})

In [52]:
new_price = model1.predict(new_house)

print("Predicted House Price:", new_price[0])

Predicted House Price: 50159000.000000015

In [53]:
import joblib

joblib.dump(model1, 'house_price_model.pkl')

['house_price_model.pkl']

In [54]:
import os
print(os.path.exists('house_price_model.pkl'))

True